### ISSUE TITLE
Is there anyone who has used the phonemizer? Any advice, please, on how to change the code correctly

### ISSUE THREAD

**Issue by ahmeftah** [yl4579/AuxiliaryASR#8]

**Comment by yl4579** [comment]
You may refer to https://github.com/yl4579/StyleTTS/blob/main/meldataset.py as it uses phonemizer.

**Comment by ziyaad30** [comment]
> You may refer to https://github.com/yl4579/StyleTTS/blob/main/meldataset.py as it uses phonemizer.

That is all you refer someone after you changed the code from StyleTTS and projects and said nothing nor update either way. This is lame

**Comment by yl4579** [comment]
@ziyaad30 I'm sorry but this is exactly what you need to change for phonezmiers. All you need to do is change the number of tokens to 178 and use the text cleaner in that meldataset.py file. Your text also needs to be already preprocessed by phonemizer so they are in the IPA form. I will try to change this repo for phonemizer later when I get more time because I'm very busy with another project.
